import { Button } from '@nextui-org/react'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Time Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{marginTop: "24px"}}>
        Time Tracker
        <Button style={{zIndex: "0"}}>Click me</Button>
      </div>
    </>
  )
}
